apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: kafka
  labels:
    app: kafka-app
spec:
  serviceName: kafka-svc
  replicas: 3
  selector:
    matchLabels:
      app: kafka-app
  template:
    metadata:
      labels:
        app: kafka-app
    spec:
      containers:
        - name: kafka-container
          image: bitnami/kafka:latest
          ports:
            - containerPort: 9090
            - containerPort: 9091
          env:
            - name: REPLICAS
              value: '3'
            - name: SERVICE
              value: kafka-svc
            - name: NAMESPACE
              value: kafka
            - name: SHARE_DIR
              value: /mnt/kafka
            - name: KAFKA_KRAFT_CLUSTER_ID
              value: 6PMpHYL9QkeyXRj9Nrp4KA
            - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
              value: "CONTROLLER:PLAINTEXT, PLAINTEXT:PLAINTEXT"
            - name: KAFKA_CFG_PROCESS_ROLES
              value: "controller,broker"
            - name: KAFKA_CFG_CONTROLLER_LISTENER_NAMES
              value: "CONTROLLER"
            - name: KAFKA_CFG_INTERNAL_BROKER_LISTENER_NAMES
              value: "PLAINTEXT"
            - name: KAFKA_CFG_LISTENERS
              value: PLAINTEXT://:9090,CONTROLLER://:9091
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: KAFKA_CFG_ADVERTISED_LISTENERS
              value: "PLAINTEXT://$(POD_NAME).kafka-svc.kafka.svc.cluster.local:9090"
            - name: KAFKA_CFG_NODE_ID
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.labels['apps.kubernetes.io/pod-index']
            - name: KAFKA_CFG_CONTROLLER_QUORUM_VOTERS
              value: "0@kafka-0.kafka-svc.kafka.svc.cluster.local:9091,1@kafka-1.kafka-svc.kafka.svc.cluster.local:9091,2@kafka-2.kafka-svc.kafka.svc.cluster.local:9091"
            - name: DEFAULT_REPLICATION_FACTOR
              value: '3'
            - name: DEFAULT_MIN_INSYNC_REPLICAS
              value: '2'
          volumeMounts:
            - name: data
              mountPath: /mnt/kafka
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: "1Gi"
  updateStrategy:
    type: RollingUpdate
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-svc
  namespace: kafka
  labels:
    app: kafka-app
spec:
  clusterIP: None
  ports:
    - name: '9090'
      port: 9090
      protocol: TCP
      targetPort: 9090
    - name: '9091'
      port: 9091
      protocol: TCP
      targetPort: 9091
  selector:
    app: kafka-app