apiVersion: v1
kind: PersistentVolume
metadata:
  name: request-db-pv
  namespace: smartbuy
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/request-db
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: request-db-pvc
  namespace: smartbuy
spec:
  volumeName: request-db-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: request-db-svc
  namespace: smartbuy
spec:
  type: NodePort
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 32541
  selector:
    app: request-db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: request-db-deployment
  namespace: smartbuy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: request-db
  template:
    metadata:
      labels:
        app: request-db
    spec:
      containers:
        - name: request-db
          image: postgres:16.1
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: request-service-secret
                  key: .REQUEST_DB_NAME
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: request-service-secret
                  key: .REQUEST_DB_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: request-service-secret
                  key: .REQUEST_DB_PASSWORD
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: request-db-storage
      volumes:
        - name: request-db-storage
          persistentVolumeClaim:
            claimName: request-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: smartbuy-request-service-svc
  namespace: smartbuy
spec:
  type: NodePort
  ports:
    - port: 8090
      targetPort: 8090
      nodePort: 32090
  selector:
    app: request-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: smartbuy-request-service-deployment
  namespace: smartbuy
spec:
  selector:
    matchLabels:
      app: request-service
  replicas: 1
  template:
    metadata:
      labels:
        app: request-service
    spec:
      containers:
        - name: request-service
          image: petrutiksa/smart-buy-request-service
          env:
            - name: REQUEST_DB
              valueFrom:
                secretKeyRef:
                  name: request-service-secret
                  key: .REQUEST_DB_NAME
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://request-db-svc.smartbuy:5432/$(REQUEST_DB)"
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: request-service-secret
                  key: .REQUEST_DB_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: request-service-secret
                  key: .REQUEST_DB_PASSWORD
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka-0.kafka-svc.kafka.svc.cluster.local:9090,kafka-1.kafka-svc.kafka.svc.cluster.local:9090"
          ports:
            - containerPort: 8090
      initContainers:
        - name: init-request-db
          image: busybox:1.28
          command: [ 'sh', '-c', "until nslookup request-db-svc.smartbuy.svc.cluster.local; do echo waiting for request-db; sleep 2; done" ]