spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      bootstrap: ${KAFKA_BOOTSTRAP_SERVERS}
      group-id: scheduler-service-event
      properties:
        spring:
          json:
            trusted:
              packages: ru.petrutik.smartbuy.event.sheduler
smartbuy:
  kafka:
    topic:
      name:
        scheduler:
          request: scheduler-event-request-topic