spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      bootstrap: ${KAFKA_BOOTSTRAP_SERVERS}
      group-id: scheduler-service-event
smartbuy:
  kafka:
    topic:
      name:
        scheduler:
          request: scheduler-event-request-topic
  schedule:
    cron:
      update: ${CRON_UPDATE}
      notify: ${CRON_NOTIFY}
      timezone: ${CRON_TIMEZONE}