server:
  port: 8080
smartbuy:
  bot:
    name: ${SMARTBUYBOT_NAME}
    token: ${SMARTBUYBOT_TOKEN}
  kafka:
    topic:
      name:
        user:
          request: user-request-topic
          response: user-response-topic

spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      bootstrap: ${KAFKA_BOOTSTRAP_SERVERS}
      group-id: user-response-event