services:
  smart-buy-parse-service:
    build: ./
    image: smart-buy-scheduler-service
    container_name: smart-buy-scheduler-service
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka-1:9090,kafka-2:9090
      - CRON_UPDATE=0 0 3 * * ?
      - CRON_NOTIFY=0 30 14 * * ?
      - CRON_TIMEZONE=Europe/Moscow
    networks:
      - kafka
      - schedule

networks:
  kafka:
    external: true
    name: smartbuy-kafka
  schedule: